app:
  replicas: 1
  env: dev
  image: nginx
  compute:
    limits:
      cpu: 0.2
      memory: 500Mi
    requests:
      cpu: 0.2
      memory: 500Mi


hpa:
  enabled: true
  maxReplicas: 10
  minReplicas: 4 
  targetCPUUtilizationPercentage: 50