# Source: ui-deploy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui-dep
  labels:
  {{- include "ui.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
      {{- include "ui.labels" . | nindent 8 }}
    spec:
      containers:
        - name: react-ui
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          resources:
          {{- toYaml .Values.app.compute | nindent 12 }}